optitrack_pose_beacon_node:
  ros__parameters:
    server_ip: 10.205.3.3
    client_ip: 10.205.3.45
    server_type: unicast
    frame_id: optitrack
    planar_x_axis: x
    planar_y_axis: z
    forward_axis: x
    robot_id: r3
    # NOTE: capital "I", not lowercase "L" -- this is how Motive spells it.
    rigid_body_name: AIfred_umh
